### ISSUE TITLE
404 issue after service and route creation for admin api.

### ISSUE THREAD

**Issue by doctormacky** [pocketdigi/kong-admin-ui#11]
<img width="759" alt="图片" src="https://user-images.githubusercontent.com/3380539/70609805-67e70e80-1c3d-11ea-9345-77205f3c7982.png">

<img width="859" alt="图片" src="https://user-images.githubusercontent.com/3380539/70609832-7503fd80-1c3d-11ea-8d88-34af539eef54.png">

<img width="958" alt="图片" src="https://user-images.githubusercontent.com/3380539/70609852-7d5c3880-1c3d-11ea-847b-4242dcf9a3e4.png">

<img width="897" alt="图片" src="https://user-images.githubusercontent.com/3380539/70609773-569e0200-1c3d-11ea-8ccf-f6086025c182.png">

**Comment by pocketdigi** [comment]
提供转发不是kong admin ui的功能，确保自己服务没有问题
