### ISSUE TITLE
项目网址

### ISSUE THREAD

**Issue by taojy123** [pocketdigi/kong-admin-ui#13]
现在网址 https://www.pocketdigi.com 是你的博客主页
建议改成 http://kong-admin.pocketdigi.com/ 项目 demo 
或者 https://www.pocketdigi.com/20190111/1637.html 这篇博文吧

**Comment by wenerme** [comment]
因为这个项目处理 2.x 的接口有些问题，也自己做了个管理后台，感兴趣可以试试 https://apis.wener.me/kong/admin  https://github.com/wenerme/apis

**Comment by taojy123** [comment]
@wenerme  
哈哈 我也有个和你类似的项目
https://tools.athenagu.com/

**Comment by wenerme** [comment]
👍 不过我的没有国内备案～
