### ISSUE TITLE
admin-ui最新bug

### ISSUE THREAD

**Issue by svenzhou1** [pocketdigi/kong-admin-ui#18]
我在使用kong jwt的时候，发现在设置header token信息报错
![image](https://user-images.githubusercontent.com/58070741/92846556-ca627a80-f41a-11ea-97d1-08459ebd5013.png)
我猜想是之前后端返回的是array，现在返回了set；但是前端接受set，
![image](https://user-images.githubusercontent.com/58070741/92846713-f120b100-f41a-11ea-8445-748062796d23.png)
但是没有处理set，希望fix这个问题，我目前是添加了set处理
![image](https://user-images.githubusercontent.com/58070741/92846788-0564ae00-f41b-11ea-85db-b35fa7f18a45.png)

**Comment by pocketdigi** [comment]
已修复
