### ISSUE TITLE
关于jwt不能设置到服务配置对应到消费者

### ISSUE THREAD

**Issue by svenzhou1** [pocketdigi/kong-admin-ui#19]
发现jwt在配置到时候
case1:没指定消费者，是所有消费者的token都可以访问到所有服务。
case2:指定消费者，发现不需要token都可以访问到所有服务（如果在消费者页面加jwt，不能访问任何服务）

**Comment by pocketdigi** [comment]
kong admin ui只是一个配置工具，至于配置后对应的效果，是由Kong实现的
