### ISSUE TITLE
建议加个账号体系

### ISSUE THREAD

**Issue by zhusaidong** [pocketdigi/kong-admin-ui#4]
不应该无验证直接访问Kong管理接口，加一层service层

**Comment by majulong** [comment]
借个楼 请问custom headers在哪找

**Comment by pocketdigi** [comment]
> 不应该无验证直接访问Kong管理接口，加一层service层

有验证，kong代理自己的admin api,加上Basic Authentication插件和Cors插件，账号密码通过custom header传。这个项目是纯前端项目，不会考虑加服务端的内容。

**Comment by pocketdigi** [comment]
> 借个楼 请问custom headers在哪找

稍后我写个教程吧

**Comment by pocketdigi** [comment]
@zhusaidong @majulong  参考  https://www.pocketdigi.com/20190613/1644.html  需要更新到0.4.0版本
