### ISSUE TITLE
浏览器不设置自定义头部信息导致功能异常

### ISSUE THREAD

**Issue by kitikousei** [pocketdigi/kong-admin-ui#5]
google chrome  72.0.3626.81
使用http://kong-admin.pocketdigi.com/#/config        首次配置api的url，不设置自定义头部信息。
在local storage中“headers”为”undefined“ 会导致打开任何页面时解析headers失败。提示
”SyntaxError: Unexpected token u in JSON at position 0“，手工去浏览器清空undefined，页面功能正常使用

**Comment by kitikousei** [comment]
另外一个异常:
操作路径："Route List"选中一条Route，点击"view",页面会返回控制台首页，
console提示错误

<img width="1163" alt="Route" src="https://user-images.githubusercontent.com/3617913/59170712-7cedc280-8b72-11e9-946a-7818da351231.png">

**Comment by pocketdigi** [comment]
> google chrome 72.0.3626.81
> 使用http://kong-admin.pocketdigi.com/#/config 首次配置api的url，不设置自定义头部信息。
> 在local storage中“headers”为”undefined“ 会导致打开任何页面时解析headers失败。提示
> ”SyntaxError: Unexpected token u in JSON at position 0“，手工去浏览器清空undefined，页面功能正常使用

默认情况下，是不存在headers的，不会有"undefined",配置的时候，如果不是JSON，也保存不了，请问是什么情况下保存了“undefined”进去？

**Comment by pocketdigi** [comment]
> google chrome 72.0.3626.81
> 使用http://kong-admin.pocketdigi.com/#/config 首次配置api的url，不设置自定义头部信息。
> 在local storage中“headers”为”undefined“ 会导致打开任何页面时解析headers失败。提示
> ”SyntaxError: Unexpected token u in JSON at position 0“，手工去浏览器清空undefined，页面功能正常使用

已找到问题，下个版本会解决

**Comment by pocketdigi** [comment]
> 另外一个异常:
> 操作路径："Route List"选中一条Route，点击"view",页面会返回控制台首页，
> console提示错误
> 
> <img alt="Route" width="1163" src="https://user-images.githubusercontent.com/3617913/59170712-7cedc280-8b72-11e9-946a-7818da351231.png">

这个问题没有发现，可以发下配置么？可能我这没测到

**Comment by kitikousei** [comment]
> > 另外一个异常:
> > 操作路径："Route List"选中一条Route，点击"view",页面会返回控制台首页，
> > console提示错误
> > <img alt="Route" width="1163" src="https://user-images.githubusercontent.com/3617913/59170712-7cedc280-8b72-11e9-946a-7818da351231.png">
> 
> 这个问题没有发现，可以发下配置么？可能我这没测到

应该是Route配置问题，没Route名字的这三个，点击会出现以上错误，其他配置了name的可以正常跳转到view
<img width="1182" alt="Route" src="https://user-images.githubusercontent.com/3617913/59260361-1057ee00-8c6e-11e9-9b42-58f676acb843.png">

**Comment by pocketdigi** [comment]
> > > 另外一个异常:
> > > 操作路径："Route List"选中一条Route，点击"view",页面会返回控制台首页，
> > > console提示错误
> > > <img alt="Route" width="1163" src="https://user-images.githubusercontent.com/3617913/59170712-7cedc280-8b72-11e9-946a-7818da351231.png">
> > 
> > 
> > 这个问题没有发现，可以发下配置么？可能我这没测到
> 
> 应该是Route配置问题，没Route名字的这三个，点击会出现以上错误，其他配置了name的可以正常跳转到view
> <img alt="Route" width="1182" src="https://user-images.githubusercontent.com/3617913/59260361-1057ee00-8c6e-11e9-9b42-58f676acb843.png">

这条Route应该不是用kong admin ui创建的，没有path字段，下个版本一起修复掉
