### ISSUE TITLE
npm run serve报错

### ISSUE THREAD

**Issue by qinshiheng** [pocketdigi/kong-admin-ui#6]
$ npm run serve

> kong-admin-ui@0.3.0 serve /app/kong-admin/kong-admin-ui
> vue-cli-service serve

/app/kong-admin/kong-admin-ui/node_modules/open/index.js:11
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/kong-admin/kong-admin-ui/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)

npm ERR! Linux 3.10.0-693.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! kong-admin-ui@0.3.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kong-admin-ui@0.3.0 serve script 'vue-cli-service serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kong-admin-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kong-admin-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kong-admin-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/kong-admin/kong-admin-ui/npm-debug.log

==============================

npm install 结果：

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by pocketdigi** [comment]
把根目录下的package-lock.json删除，再npm install 试试

**Comment by mingkeming** [comment]
> 把根目录下的package-lock.json删除，再npm install 试试
我这的版本出现的错误和那个人的很象

日志如下

> kong-admin-ui@0.3.0 serve /usr/kongadmin/kong-admin-ui-master
> vue-cli-service serve

/usr/kongadmin/kong-admin-ui-master/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                                                      ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/kongadmin/kong-admin-ui-master/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kong-admin-ui@0.3.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kong-admin-ui@0.3.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-29T03_04_55_907Z-debug.log




0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'serve' ]
2 info using npm@6.10.2
3 info using node@v6.17.1
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle kong-admin-ui@0.3.0~preserve: kong-admin-ui@0.3.0
6 info lifecycle kong-admin-ui@0.3.0~serve: kong-admin-ui@0.3.0
7 verbose lifecycle kong-admin-ui@0.3.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle kong-admin-ui@0.3.0~serve: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/kongadmin/kong-admin-ui-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle kong-admin-ui@0.3.0~serve: CWD: /usr/kongadmin/kong-admin-ui-master
10 silly lifecycle kong-admin-ui@0.3.0~serve: Args: [ '-c', 'vue-cli-service serve' ]
11 silly lifecycle kong-admin-ui@0.3.0~serve: Returned: code: 1  signal: null
12 info lifecycle kong-admin-ui@0.3.0~serve: Failed to exec serve script
13 verbose stack Error: kong-admin-ui@0.3.0 serve: `vue-cli-service serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid kong-admin-ui@0.3.0
15 verbose cwd /usr/kongadmin/kong-admin-ui-master
16 verbose Linux 3.10.0-957.21.3.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
18 verbose node v6.17.1
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error kong-admin-ui@0.3.0 serve: `vue-cli-service serve`
22 error Exit status 1
23 error Failed at the kong-admin-ui@0.3.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

这里是有特殊的依赖吗？

**Comment by mingkeming** [comment]
@qinshiheng 你的node版本太低了，你换高点再试一下
