### ISSUE TITLE
添加rs256算法的jwt公钥失败

### ISSUE THREAD

**Issue by xljiulang** [pocketdigi/kong-admin-ui#7]
首先，非常感谢你这个作品，在我使用过程中，发现了几个小小缺陷

- plugs列表的enabled属性永远为false
- 当plug实例不关联service时，查看pulg详情会跳转到登录界面
- 添加之后的插件，查看详情并直接保存，提示各字段期待为集合类型（field xxx expected a set）
- consumer添加JWT credentials提示公钥无效，但我试着使用postMan的form-data提交是成功的

**Comment by pocketdigi** [comment]
1. plugins列表里有enable展示的是插件本身是否启用，控件本身是disable的，只做展示插件启用状态，不可开启关闭插件。实测是可以正确显示是否启用插件的。
2. 这个问题在于，不选择service,kong会应用到所有service上。如果你访问admin api是通过配置kong的service转发的，当前配置的插件也会应用到这个service上，如果是权限插件，kong admin ui就没权限访问。
3. 哪个插件？测了好几个，没发现问题
4. 未发现问题

上面测试基于kong 1.1.2 kong admin ui是 http://kong-admin.pocketdigi.com ，请提供你的版本号
