### ISSUE TITLE
添加ROUTE出错

### ISSUE THREAD

**Issue by baitly002** [pocketdigi/kong-admin-ui#8]
在添加路由的时候，出现以下情况
Request URL: http://192.168.1.17:8001/routes/
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 192.168.1.17:8001
Referrer Policy: no-referrer-when-downgrade
**Request Payload:**
destinations: []
hosts: []
methods: ["GET", "POST"]
name: "client"
paths: ["/"]
preserve_host: false
protocols: ["http", "https"]
regex_priority: 0
service: {id: "9ccf388b-e72a-4d06-a5a5-850a4a657cec"}
snis: []
sources: []
strip_path: true
**返回的错误是：**
{
    "message": "2 schema violations (destinations: cannot set 'destinations' when 'protocols' is 'http' or 'https'; sources: cannot set 'sources' when 'protocols' is 'http' or 'https')",
    "name": "schema violation",
    "fields": {
        "destinations": "cannot set 'destinations' when 'protocols' is 'http' or 'https'",
        "sources": "cannot set 'sources' when 'protocols' is 'http' or 'https'"
    },
    "code": 2
}
**原因：**
表单无论在什么情况下，都提交了sources和destinations参数，在某种情况下，这两参数不应提交的

**Comment by linyzeng** [comment]
同样的问题出现在 kong 1.3.0 版本

**Comment by chjw8016** [comment]
同问

**Comment by mjabari** [comment]
when I uncheck all protocols, it still sends an empty array as param like this:
`destinations: []`
so i think it should remove the corresponding request param when nothing is selected or input is empty. am I correct?

**Comment by pocketdigi** [comment]
> 在添加路由的时候，出现以下情况
> Request URL: http://192.168.1.17:8001/routes/
> Request Method: POST
> Status Code: 400 Bad Request
> Remote Address: 192.168.1.17:8001
> Referrer Policy: no-referrer-when-downgrade
> **Request Payload:**
> destinations: []
> hosts: []
> methods: ["GET", "POST"]
> name: "client"
> paths: ["/"]
> preserve_host: false
> protocols: ["http", "https"]
> regex_priority: 0
> service: {id: "9ccf388b-e72a-4d06-a5a5-850a4a657cec"}
> snis: []
> sources: []
> strip_path: true
> **返回的错误是：**
> {
> "message": "2 schema violations (destinations: cannot set 'destinations' when 'protocols' is 'http' or 'https'; sources: cannot set 'sources' when 'protocols' is 'http' or 'https')",
> "name": "schema violation",
> "fields": {
> "destinations": "cannot set 'destinations' when 'protocols' is 'http' or 'https'",
> "sources": "cannot set 'sources' when 'protocols' is 'http' or 'https'"
> },
> "code": 2
> }
> **原因：**
> 表单无论在什么情况下，都提交了sources和destinations参数，在某种情况下，这两参数不应提交的

1.1.2 未发现这个问题，提交空数组不影响

**Comment by neelee** [comment]
同问  一模一样的错误信息

**Comment by neelee** [comment]
version: 1.4.1  出现这样的问题

**Comment by pocketdigi** [comment]
> version: 1.4.1 出现这样的问题

后面的版本增强了校验，会修复

**Comment by pocketdigi** [comment]
已修复

**Comment by neelee** [comment]
谢谢了

**Comment by neelee** [comment]
> 已修复
谢谢了
