### ISSUE TITLE
好像有vue的跨域问题

### ISSUE THREAD

**Issue by nevenchen** [pocketdigi/kong-admin-ui#9]
用了kong dashboard, konga，对比下来还是这个好用。
但是有个问题，参考这篇文章https://www.pocketdigi.com/20190613/1644.html
设置账户的时候，输入Authorization总是请求不到，F12看到有错误：
`has been blocked by CORS policy: Request header field Access-Control-Allow-Origin is not allowed by Access-Control-Allow-Headers in preflight response.`

![image](https://user-images.githubusercontent.com/3069043/66623390-07782880-ec1e-11e9-87e5-03562927b5d6.png)

**Comment by pocketdigi** [comment]
跨域自己加cors插件

**Comment by nevenchen** [comment]
通过cors解决了

**Comment by neelee** [comment]
> 通过cors解决了

请问下怎么配置的？

**Comment by neelee** [comment]
> 通过cors解决了

请问下怎么配置的。我的配置返回的是“Access-Control-Allow-Headers: Content-Type”没有返回authorization

**Comment by neelee** [comment]
> 跨域自己加cors插件

请问下怎么配置的。我的配置返回的是“Access-Control-Allow-Headers: Content-Type”没有返回authorization
